import { tool } from '@langchain/core/tools';
// Zod v3 compat: see echo.ts.
import { z } from 'zod/v3';
import sharp from 'sharp';
import { fetchImageBuffer } from './lib/fetch-image-buffer';
import { classifyImage, HfInferenceError } from './lib/hf-inference';

const DEFAULT_MODEL = 'Organika/sdxl-detector';

const SYNTHETIC_LABELS = new Set(['artificial', 'fake', 'ai', 'synthetic', 'generated']);

async function preprocessForModel(buffer: Buffer): Promise<Buffer> {
  return await sharp(buffer)
    .removeAlpha()
    .resize(512, 512, { fit: 'inside', withoutEnlargement: false })
    .jpeg({ quality: 90 })
    .toBuffer();
}

export async function detectDiffusionGenerationFromUrl(imageUrl: string): Promise<string> {
  const modelId = process.env.DIFFUSION_DETECTOR_MODEL ?? DEFAULT_MODEL;

  const { buffer } = await fetchImageBuffer(imageUrl);
  const preprocessed = await preprocessForModel(buffer);

  let results;
  try {
    results = await classifyImage(modelId, preprocessed, { contentType: 'image/jpeg' });
  } catch (err) {
    if (err instanceof HfInferenceError && err.status === 503) {
      return `Diffusion detector temporarily unavailable (HF cold-start, status 503 after one retry). Other signals still apply.`;
    }
    throw err;
  }

  if (results.length === 0) {
    return `Diffusion detector (${modelId}): no classifications returned.`;
  }

  const top = [...results].sort((a, b) => b.score - a.score)[0];
  const syntheticEntry = results.find((r) => SYNTHETIC_LABELS.has(r.label.toLowerCase()));
  const syntheticScore = syntheticEntry?.score;

  const scoreStr =
    syntheticScore != null
      ? `synthetic_score=${syntheticScore.toFixed(3)}`
      : `top_score=${top.score.toFixed(3)}`;

  return [
    `Diffusion detector (${modelId}): top_label="${top.label}" (${top.score.toFixed(3)}), ${scoreStr}.`,
    `Threshold guidance: a synthetic-side score > 0.7 suggests diffusion-generated (SDXL/Flux/MJ/DALL-E).`,
    `Caveat: the model is trained primarily on SDXL outputs; newer generators (Flux 1.x, MJ v7) may evade. Combine with C2PA, EXIF, and PDQ for confidence.`,
  ].join(' ');
}

export const detectDiffusionGenerationTool = tool(
  async ({ image_url }) => {
    return await detectDiffusionGenerationFromUrl(image_url);
  },
  {
    name: 'detect_diffusion_generation',
    description:
      'Detect whether an image at a public URL was generated by a diffusion model (Stable Diffusion XL, Flux, Midjourney, DALL-E, Adobe Firefly, etc.). Use when you suspect an image is AI-generated — political deepfakes, fabricated news photos, suspicious profile pictures. Returns the top label, the synthetic-side score, and an explicit caveat about coverage gaps for newer generators.',
    schema: z.object({
      image_url: z.string().url().describe('Public URL of the image to classify'),
    }),
  },
);
