import { tool } from '@langchain/core/tools';
// Zod v3 compat: see echo.ts for the rationale.
import { z } from 'zod/v3';
import { z as zod4 } from 'zod';
import { Reader } from '@contentauth/c2pa-node';
import { fetchImageBuffer } from './lib/fetch-image-buffer';
import { loadTrustList, matchIssuer, type TrustedIssuer } from './lib/load-trust-list';

const ConfigSchema = zod4.object({
  trust_list_path: zod4.string().min(1).default('./config/c2pa-trust-list.yaml'),
});
export type VerifyC2paConfig = zod4.infer<typeof ConfigSchema>;

interface SignatureInfo {
  issuer?: string | null;
  time?: string | null;
  timeObject?: Date | null;
}

interface ActiveManifest {
  claim_generator?: string | null;
  signature_info?: SignatureInfo | null;
}

interface ValidationStatusEntry {
  code?: string;
  explanation?: string | null;
}

interface ManifestStoreJson {
  active_manifest?: string | null;
  manifests?: Record<string, ActiveManifest> | null;
  validation_status?: ValidationStatusEntry[] | null;
}

function formatSignedAt(sig: SignatureInfo | null | undefined): string {
  if (!sig) return '(unknown)';
  if (sig.timeObject instanceof Date) return sig.timeObject.toISOString();
  if (typeof sig.time === 'string') return sig.time;
  return '(unknown)';
}

export function classifyC2pa(
  store: ManifestStoreJson | null,
  trustList: TrustedIssuer[],
): string {
  // State 1: no manifest at all
  if (!store || !store.active_manifest || !store.manifests) {
    return 'No C2PA manifest present. This is the default for most images in circulation; absence does not imply forgery.';
  }

  const active = store.manifests[store.active_manifest];
  if (!active) {
    return 'No C2PA manifest present. This is the default for most images in circulation; absence does not imply forgery.';
  }

  const generator = active.claim_generator ?? '(unknown generator)';
  const issuer = active.signature_info?.issuer ?? null;
  const signedAt = formatSignedAt(active.signature_info);
  const validationFailures = (store.validation_status ?? []).filter(
    (s) => typeof s.code === 'string' && s.code.length > 0,
  );

  // State 4: signature failed validation
  if (validationFailures.length > 0) {
    const codes = validationFailures.map((s) => s.code).join(', ');
    return `C2PA manifest present but signature verification FAILED. Codes: ${codes}. Strong indicator of tampering or forged credentials.`;
  }

  // State 2: valid signature from trusted issuer
  const trusted = matchIssuer(issuer, trustList);
  if (trusted) {
    return `C2PA manifest verified. Generator: ${generator}. Issuer: "${issuer}" (trusted, category=${trusted.category}). Signed: ${signedAt}. High-confidence provenance.`;
  }

  // State 3: valid signature from unrecognized issuer
  return `C2PA manifest present and cryptographically valid, but signed by issuer not in our trust list ("${issuer ?? 'unknown'}"). Signature intact; we cannot vouch for issuer authority. Treat as a soft signal.`;
}

export function createVerifyC2paTool(rawConfig?: unknown) {
  const config = ConfigSchema.parse(rawConfig ?? {});

  return tool(
    async ({ image_url }) => {
      const { buffer, mimeType } = await fetchImageBuffer(image_url);

      let reader: Reader | null;
      try {
        reader = await Reader.fromAsset({ buffer, mimeType });
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        // c2pa-rs throws on totally unparseable assets; treat as "no manifest"
        // unless the message indicates a deeper problem.
        if (/no claim/i.test(msg) || /no provenance/i.test(msg)) {
          reader = null;
        } else {
          throw new Error(`C2PA read error: ${msg}`);
        }
      }

      const store = reader ? (reader.json() as unknown as ManifestStoreJson) : null;
      const trustList = loadTrustList(config.trust_list_path);
      return classifyC2pa(store, trustList);
    },
    {
      name: 'verify_c2pa_credentials',
      description:
        'Verify cryptographic C2PA Content Credentials (provenance signature) of an image at a public URL. Use whenever you need to know the origin of an image — was it taken by a camera (Sony/Nikon/Leica/Canon), edited in Photoshop, generated by OpenAI/DALL-E/Midjourney/Google, or published by a trusted news outlet (NYT/BBC/Reuters/AP). Should be the FIRST check on any suspicious image because it is fast, local, and cryptographic. Returns one of four states: no manifest, valid+trusted issuer, valid+untrusted issuer, or tampering detected.',
      schema: z.object({
        image_url: z.string().url().describe('Public URL of the image to verify'),
      }),
    },
  );
}
